### ISSUE TITLE
Add deploy.yml default variable setting in Docs

### ISSUE THREAD

**Issue by UsadaPeko** [gitploy-io/gitploy#427]
**Is your feature request related to a problem? Please describe.**

롤백을 하고싶은 경우, auto_merge를 따로 설정하지 않았음에도 불구하고 자동으로 merge가 진행되었습니다. 
auto_merge의 기본 설정을 확인하기 위하여 문서를 보았으나, 롤백시에 false로 설정하라는 이야기밖에 없었습니다.

**Describe the solution you'd like**

가시성을 위하여 기본 값이 어떻게 설정되어있는지 문서에 같이 명시하면 좋겠습니다.

**Additional context**

**Comment by hanjunlee** [comment]
@UsadaPeko Thank you for your contribution.
